const People = [
  {
    id: 1,
    image: "http://image.com",
    name: "Isaac Neuton",
    jobTitle: "developer",
    membership: "member",
    task: 23,
  },
  {
    id: 2,
    image: "http://image1.com",
    name: "Moses Daniel",
    jobTitle: "devops engineer",
    membership: "member",
    task: 232,
  },
  {
    id: 3,
    image: "http://image2.com",
    name: "Donald Trump",
    jobTitle: "cloud engineer",
    membership: "member",
    task: 123,
  },
  {
    id: 4,
    image: "http://image3.com",
    name: "George Bushe",
    jobTitle: "Designer",
    membership: "member",
    task: 223,
  },
  {
    id: 5,
    image: "http://image4.com",
    name: "Moham Buhar",
    jobTitle: "barrow pusher",
    membership: "member",
    task: 323,
  },
  {
    id: 6,
    image: "http://image5.com",
    name: "spencer Herb",
    jobTitle: "Philosopher",
    membership: "member",
    task: 423,
  },
  {
    id: 7,
    image: "http://image5.com",
    name: "spencer Herb",
    jobTitle: "Philosopher",
    membership: "member",
    task: 423,
  },
  {
    id: 8,
    image: "http://image5.com",
    name: "spencer Herb",
    jobTitle: "Philosopher",
    membership: "member",
    task: 423,
  },
  {
    id: 9,
    image: "http://image5.com",
    name: "spencer Herb",
    jobTitle: "Philosopher",
    membership: "member",
    task: 423,
  },
];

export default People;
