const People = [
  {
    id: 1,
    image: "http://image.com",
    name: "Isaac Neuton",
    jobTitle: "Developer",
    membership: "member",
    task: 23,
  },
  {
    id: 2,
    image: "http://image1.com",
    name: "Moses Daniel",
    jobTitle: "Devops Engineer",
    membership: "member",
    task: 232,
  },
  {
    id: 3,
    image: "http://image2.com",
    name: "Donald Trump",
    jobTitle: "Cloud Engineer",
    membership: "member",
    task: 123,
  },
  {
    id: 4,
    image: "http://image3.com",
    name: "George Bushe",
    jobTitle: "Designer",
    membership: "member",
    task: 223,
  },
  {
    id: 5,
    image: "http://image4.com",
    name: "Moham Buhar",
    jobTitle: "Barrow Pusher",
    membership: "member",
    task: 323,
  },
  {
    id: 6,
    image: "http://image5.com",
    name: "Paul Labille",
    jobTitle: "Front-end Engineer",
    membership: "member",
    task: 423,
  },
  {
    id: 7,
    image: "http://image5.com",
    name: "Spencer Herb",
    jobTitle: "Philosopher",
    membership: "member",
    task: 423,
  },
  {
    id: 8,
    image: "http://image5.com",
    name: "Phil Jones",
    jobTitle: "Philosopher",
    membership: "member",
    task: 423,
  },
  {
    id: 9,
    image: "http://image5.com",
    name: "Chris Eagles",
    jobTitle: "Philosopher",
    membership: "member",
    task: 423,
  },
];

export default People;
